name: Update Rules

on:
  push:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  make_rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Rules and Git push assets to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
        run: |
          bash ./shell/make.sh
          git config --local user.name "action"
          git config --local user.email "action@github.com"
          git add --all
          git commit -m "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          git push --force

  manual_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Manual-Update AdRules Repository
        run: bash ./shell/manual-update.sh
