jobs:
  merge-rules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run merge script
      run: |
        export TZ=Asia/Shanghai  # 设置时区
        python merge_rules.py
        echo "规则更新时间: $(date +'%Y-%m-%d %H:%M:%S%:z')" >> update.log
        ls -la merged-filter.txt update.log

    - name: Commit changes
      run: |
        git config --global --add safe.directory /github/workspace
        git config --global user.name "AutoUpdater[Bot]"
        git config --global user.email "916899380+autoupdater[bot]@users.noreply.github.com"
        git add merged-filter.txt update.log
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "自动更新规则: $(date -u '+%Y-%m-%d')"
          git push
        else
          echo "无变更可提交"
        fi